### ISSUE TITLE
初始化失败

### ISSUE THREAD

**Issue by mayerui** [numbaa/NaiveGame#3]
项目里没有带资源文件，希望readme里写详细一点

**Comment by numbaa** [comment]
是的，我们特地不把资源文件方式放上去，当初托管在Github上很大原因只是为了方便协作。
我手上这台电脑也没有资源文件，你可以让MemeTao给你单独发一份。

另外就是，编程经验稍微上来一点后，我发现这个项目在设计上存在很多问题。
我暂时的想法是给它打一个TAG，然后重新设计。

2017-12-30 12:05 GMT+08:00 mohuang <notifications@github.com>:
